rlRun_LOG defined and deleted as an array
beakerlib/beakerlib pull request #106
Opened 2021-08-30 14:59 UTC by 4N0body5

temporary files are grouped in an array rlRun_LOG (by the prepend method) that is afterwards deleted at once in rlJournal End (so it does not require manual removal)

2021-08-31 08:04 UTC, sopos requested changes

2021-08-31 08:04 UTC, sopos commented on src/journal.sh
> +    fi
nicer and consistent code formating
```suggestion
    if (( ${#rlRun_LOG[@]} )); then
        rm -f "${rlRun_LOG[@]}"
        rlLogInfo "Deleting rlRun_LOG file(s)"
        local tmp_LOG=${rlRun_LOG[*]}
        rlLogDebug "Deleting temporary file(s) ${tmp_LOG// /, }"
    fi
```

2021-08-31 12:07 UTC, sopos commented on src/journal.sh
> +    fi
Could you also update the documentation of `rlRun` to inform user about the deletion of the files in `rlJournalEnd`?

2021-08-31 15:17 UTC, sopos requested changes

2021-08-31 15:17 UTC, sopos commented on src/testing.sh
> +When -t option is used, the content of the file becomes tagged too.
```suggestion
it on a terminal) and set $rlRun_LOG variable to name of the file. $rlRun_LOG
is now actually an array where the first index holds the last reference to the file.
Thus its behavior is not changed if used without an index. The array is consumed by
the rlJournalEnd function to remove the leftover files, so no manual files removal
is needed anymore.
Note that if you need to use such a file after calling the rlJournalEnd function
you need to create your own copy of the respective file.
When -t option is used, the content of the file becomes tagged too.
```

2021-08-31 20:27 UTC, sopos approved these changes

2021-08-31 20:28 UTC, merged

2021-09-01 15:19 UTC, psss commented
Very nice and elegant backward-compatible solution! Thanks for improving this.