Replacing chkconfig commnand with systemctl
beakerlib/beakerlib pull request #88
Opened 2021-01-27 14:10 UTC by hegerj

2021-01-27 14:12 UTC, hegerj commented
There are still functions called `chkconfig()` in test/infrastructureTest.sh but I am not sure how that works because it doesn't seem that they are called...? Anyway they do not call `chkconfig` command itself so it should not be a problem.

2021-01-27 17:55 UTC, sopos commented
> There are still functions called `chkconfig()` in test/infrastructureTest.sh but I am not sure how that works because it doesn't seem that they are called...? Anyway they do not call `chkconfig` command itself so it should not be a problem.

Those should be just a fake funftions for the testing purposes (not to mess with the system).

2021-01-27 18:06 UTC, sopos commented
I'm a bit afraid just replacing it might not be a good idea as it may not work correctly with older rhels. Namely rhel6 do not use `systemctl` at all and we recently needed to created rhel6 build.

I would prefer similar solution as [__INTERNAL_SERVICE](https://github.com/beakerlib/beakerlib/blob/master/src/infrastructure.sh#L969) with a [fallback](https://github.com/beakerlib/beakerlib/blob/master/src/infrastructure.sh#L979) if the want command does not exist.

Such approach would prefer the old way if available. This may prevent similar situations as `service auditd stop` vs. `systemctl stop auditd` where systemctl does not correctly.

2021-01-27 18:35 UTC, sopos requested changes

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
something like
```suggestion
# __INTERNAL_CHKCONFIG operation..
# a translation layer from systemctl-like call to chkconfig
# note that the parameters order is matching systemctl
# $1 - operation
# $2 - service
__INTERNAL_CHKCONFIG() {
  local svc="$2" op
  case $1 in
    is-enabled)
      op=""
    ;;
    enable)
      op="on"
    ;;
    disable)
      op="off"
    ;;
    *)
      rlLogError "chkconfig: operation not implement, please cover!"
    ;;
  esac
  chkconfig "$svc" $op
}
which chkconfig >/dev/null 2>&1 || __INTERNAL_CHKCONFIG() { __INTERNAL_SYSTEMCTL "$@"; }
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +      systemctl is-enabled $service > /dev/null
```suggestion
      __INTERNAL_CHKCONFIG is-enabled $service > /dev/null
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +      if systemctl enable "$service"; then
```suggestion
      if __INTERNAL_CHKCONFIG enable "$service"; then
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +        systemctl is-enabled $service > /dev/null
```suggestion
        __INTERNAL_CHKCONFIG is-enabled $service > /dev/null
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +        if systemctl disable "$service"; then
```suggestion
        if __INTERNAL_CHKCONFIG disable "$service"; then
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +      rlServiceStart xinetd && systemctl enable ${serviceName}
```suggestion
      rlServiceStart xinetd && __INTERNAL_CHKCONFIG enable ${serviceName}
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +      systemctl is-enabled ${serviceName} > /dev/null;   local outcome=$?
```suggestion
      __INTERNAL_CHKCONFIG is-enabled ${serviceName} > /dev/null;   local outcome=$?
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +      systemctl disable ${serviceName}
```suggestion
      __INTERNAL_CHKCONFIG disable ${serviceName}
```

2021-01-27 18:35 UTC, sopos commented on src/infrastructure.sh
> +        systemctl is-enabled ${serviceName} > /dev/null;   local outcome=$?
```suggestion
        __INTERNAL_CHKCONFIG is-enabled ${serviceName} > /dev/null;   local outcome=$?
```

2021-01-28 11:16 UTC, hegerj commented
I realise the RHEL6 doesn't have systemd however I thought it would be better to patch the problem on potential next RHEL6 release rather then do full release. It might be bit more work then rebase but at the cost of adding another 'wrapper' function as you suggested that, in my opinion, makes the code quite hard to understand (constant jumping from function to function, overriding and nested functions makes it harder to find issues/read the code).
But if you think this solution is better we can do it. 
Good catch about `__INTERNAL_SYSTEMCTL` which I should have used.

2021-01-28 19:19 UTC, sopos commented
The thing is that now we have a common spec file so the doing a rebase in downstream is easier than adding patches. But we can crate the patch even in the upstream and distribute it along way.

2021-01-28 20:12 UTC, sopos commented
I'm not really sure which which approach would be better. In case of RHEL, there's `chkconfig` available in RHEL-8 as well. So we might be all but Fedora?

2021-01-29 11:27 UTC, hegerj commented
> The thing is that now we have a common spec file so doing a rebase in downstream is easier than adding patches. But we can create the patch even in the upstream and distribute it along the way. However I consider maintaining a patch more demanding.

ok, that makes sense, no patching then

> I'm not really sure which which approach would be better. In case of RHEL, there's chkconfig available in RHEL-8 as well. So we might be all but Fedora?

Not sure what you mean but `chkconfig` is available on all Fedoras (31,32,33) it's just not installed by default I guess.

2021-01-29 13:34 UTC, sopos commented
> Not sure what you mean but `chkconfig` is available on all Fedoras (31,32,33) it's just not installed by default I guess.

fixed the text in the original comment

`chkconfi`g may be installed on Fedora but I'm talking about the fact that `chkconfig` is installed by _default_ in some distro versions. Apparently it was by default installed on Fedora upto 33 but currently Fedora 34 does not.

2021-01-29 13:50 UTC, sopos commented
I've provided a commit implementing the falback mechanism, its main advantage is virtually no additional action in case of downstream build since rhel6.

2021-01-29 13:50 UTC, sopos approved these changes

2021-01-29 14:05 UTC, merged